// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBi2VyFUvJWNvD-xpCQYQtDaYf2pLNfk',
    appId: '1:86506563533:web:7a9b1bf9d48dfcc73c0684',
    messagingSenderId: '86506563533',
    projectId: 'brahma-app-3f6bf',
    authDomain: 'brahma-app-3f6bf.firebaseapp.com',
    storageBucket: 'brahma-app-3f6bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe4v521waGY_zkXcXah8LwJ6b8b2-tDwk',
    appId: '1:86506563533:android:9c974c5eb189becf3c0684',
    messagingSenderId: '86506563533',
    projectId: 'brahma-app-3f6bf',
    storageBucket: 'brahma-app-3f6bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEGRWb0U5oMPiFr9iTKLcHpXtSvIUQIzE',
    appId: '1:86506563533:ios:4688aa6fb36cd4b33c0684',
    messagingSenderId: '86506563533',
    projectId: 'brahma-app-3f6bf',
    storageBucket: 'brahma-app-3f6bf.firebasestorage.app',
    androidClientId: '86506563533-krldtfn3bfm7rj7molsimb0j9dt08hbs.apps.googleusercontent.com',
    iosClientId: '86506563533-ss2f8ji6a3j1us7rt767gu1jrrvkt4rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.brahmaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEGRWb0U5oMPiFr9iTKLcHpXtSvIUQIzE',
    appId: '1:86506563533:ios:4688aa6fb36cd4b33c0684',
    messagingSenderId: '86506563533',
    projectId: 'brahma-app-3f6bf',
    storageBucket: 'brahma-app-3f6bf.firebasestorage.app',
    androidClientId: '86506563533-krldtfn3bfm7rj7molsimb0j9dt08hbs.apps.googleusercontent.com',
    iosClientId: '86506563533-ss2f8ji6a3j1us7rt767gu1jrrvkt4rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.brahmaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBi2VyFUvJWNvD-xpCQYQtDaYf2pLNfk',
    appId: '1:86506563533:web:7a9b1bf9d48dfcc73c0684',
    messagingSenderId: '86506563533',
    projectId: 'brahma-app-3f6bf',
    authDomain: 'brahma-app-3f6bf.firebaseapp.com',
    storageBucket: 'brahma-app-3f6bf.firebasestorage.app',
  );
}
